-- Baseline schema, matching the Submission and AdminUser entities as of Phase 22.
-- Column types/constraints mirror what Hibernate's ddl-auto=update previously generated for these
-- entities (Phases 3 and 16) - see AdminUserSeeder for the initial admin row, seeded by the app itself,
-- not by a migration.

CREATE TABLE submissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(200) NOT NULL,
    email       VARCHAR(255),
    phone       VARCHAR(30),
    message     TEXT,
    status      VARCHAR(20) NOT NULL CHECK (status IN ('NEW', 'IN_PROGRESS', 'COMPLETED')),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE admin_users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(100) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(30) NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_admin_users_username UNIQUE (username)
);
