-- Adds the courses table (Phase D1 - Course domain), see
-- docs/planning/plan-2-full-redesign-driveup.md.
--
-- seats_registered / a derived status column are intentionally NOT stored here - see Course.java's
-- Javadoc for why (avoids a second source of truth ahead of D2 adding Submission.course_id, which is
-- what seatsRegistered will eventually be COUNT()'d from).

CREATE TABLE courses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(200) NOT NULL,
    license_class    VARCHAR(20) NOT NULL CHECK (license_class IN ('B1', 'B2', 'C')),
    price            NUMERIC(12, 2) NOT NULL,
    duration_months  INTEGER NOT NULL,
    practice_hours   INTEGER NOT NULL,
    description      TEXT,
    branch           VARCHAR(100),
    teacher_name     VARCHAR(200),
    seats_total      INTEGER NOT NULL,
    start_date       DATE NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL
);
