-- Adds "assign submission to a consultant" (Phase B) and "internal notes" (Phase C), see
-- docs/planning/plan-3-assign-submission-notes.md. Combined into one migration since both are the same
-- feature pass (explicitly allowed by that plan).

-- Phase B: assigning a submission to an admin/consultant account is organizational only (a label), not an
-- access-control mechanism - every admin can still see/edit every submission regardless of assignment (see
-- the plan's "Quyết định thiết kế quan trọng" section). Nullable, no ON DELETE action - there's no
-- delete-admin-user flow yet, so cascading behavior on that FK isn't needed.
ALTER TABLE submissions ADD COLUMN assigned_to_id BIGINT NULL REFERENCES admin_users (id);

-- Phase C: append-only internal notes on a submission's timeline. CASCADE on submission delete (a
-- reasonable default for a child table, even though there's no delete-submission flow yet either); no
-- cascade on admin_users - deleting an admin user isn't a supported flow, so this FK is left RESTRICT
-- (the default) rather than guessing an ON DELETE behavior for a case that can't happen yet.
CREATE TABLE submission_notes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  BIGINT NOT NULL REFERENCES submissions (id) ON DELETE CASCADE,
    author_id      BIGINT NOT NULL REFERENCES admin_users (id),
    content        TEXT NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL
);
