-- Adds the payments table (SePay VietQR payment integration - not part of the original roadmap).
--
-- One submission can have multiple payment rows over time (e.g. a stale PENDING one is superseded by a
-- freshly generated one) - there is no unique constraint tying a submission to a single payment row, only
-- an index for lookup performance. sepay_transaction_id is unique (but nullable, since a PENDING payment
-- has none yet) so a webhook can never mark two different payment rows as PAID from the same bank
-- transaction.

CREATE TABLE payments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         BIGINT NOT NULL,
    amount                NUMERIC(12, 2) NOT NULL,
    status                VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    sepay_transaction_id  VARCHAR(100),
    paid_at               TIMESTAMP(6),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_payments_submission FOREIGN KEY (submission_id) REFERENCES submissions (id),
    CONSTRAINT uk_payments_sepay_transaction_id UNIQUE (sepay_transaction_id)
);

CREATE INDEX idx_payments_submission_id ON payments (submission_id);
